import { createHash } from "node:crypto";
import { EVIDENCE_CONFIDENCES, EVIDENCE_KINDS, type AcquisitionFailure, type EvidenceSegment, type LectureAcquisitionArtifact, type LectureAcquisitionPort, type LectureAcquisitionRequest, type LectureEvidenceProvider, type LectureSourceParser, type PlaylistExpander, type ResolvedVideoSource, validateLectureAcquisitionArtifact } from "@andvl1/omp-workflows-core";
import { parseYouTubeUrl } from "./youtube-url.js";
import { YouTubePlaylistExpander } from "./youtube-playlist.js";
import { GeminiYouTubeProvider } from "./gemini.js";
import { AcquisitionProviderError, isAcquisitionProviderError, safeProviderError } from "./provider-errors.js";
import { loadLectureResearchConfig, type LectureResearchConfig } from "./config.js";

type Failure = AcquisitionFailure;
const makeFailure = (code: string, message: string, extra: Partial<Failure> = {}): Failure => ({ code: code as Failure["code"], message, retryable: false, attempts: 1, severity: "error", ...extra });
const safeFailure = (e: unknown, provider?: string): Failure => { const x = safeProviderError(provider ?? "lecture-acquisition", e); return { code: x.code, message: x.message, retryable: x.retryable, attempts: 1, severity: "error", ...(provider ? { provider } : {}) }; };
export class LectureAcquisitionError extends Error { readonly failure: Failure; constructor(failure: Failure) { super(failure.message); this.name = "LectureAcquisitionError"; this.failure = { ...failure }; } }
export const isLectureAcquisitionError = (error: unknown): error is LectureAcquisitionError => error instanceof LectureAcquisitionError;

export class YouTubeLectureAcquisitionService implements LectureAcquisitionPort {
  constructor(private readonly options: { parser: LectureSourceParser; playlistExpander: PlaylistExpander; evidenceProvider: LectureEvidenceProvider; providerId?: string; model?: string; clock?: () => Date }) {}
  async acquire(request: LectureAcquisitionRequest, externalSignal?: AbortSignal): Promise<LectureAcquisitionArtifact> {
    const prompt = (request as { prompt?: unknown } | null | undefined)?.prompt;
    const promptFailure = typeof prompt !== "string"
      ? { code: "INVALID_URL" as const, message: "Lecture prompt must be a non-empty string", retryable: false, attempts: 0, severity: "error" as const }
      : prompt.length > 16_384
        ? { code: "LIMIT_EXCEEDED" as const, message: "Lecture prompt exceeds the maximum allowed length", retryable: false, attempts: 0, severity: "error" as const }
        : prompt.trim().length === 0
          ? { code: "INVALID_URL" as const, message: "Lecture prompt must be a non-empty string", retryable: false, attempts: 0, severity: "error" as const }
          : undefined;
    if (promptFailure) throw new LectureAcquisitionError(promptFailure);
    const clock = this.options.clock ?? (() => new Date()); const startedAt = clock(); const parsed = this.options.parser.parse(request.sourceUrl);
    if (!("kind" in parsed)) throw new LectureAcquisitionError(parsed);
    const controller = new AbortController(); const effectiveSignal = externalSignal ?? new AbortController().signal; const abort = () => controller.abort(); effectiveSignal.addEventListener("abort", abort, { once: true }); if (effectiveSignal.aborted) controller.abort(); const timer = setTimeout(() => controller.abort(), request.limits.deadlineMs);
    const provider = { id: this.options.providerId ?? this.options.evidenceProvider.id, ...(this.options.model ? { model: this.options.model } : {}) };
    const requestShape = { sourceUrl: request.sourceUrl, canonicalUrl: parsed.canonicalUrl, sourceKind: parsed.kind, prompt: request.prompt, limits: request.limits };
    try {
      if (!request.rights.automatedPublicVideoAnalysisApproved) {
        const sourceSet = parsed.kind === "playlist" ? { requested: parsed, items: [], truncated: false, failures: [] } : { requested: parsed, items: [{ sourceId: `yt-video-${parsed.videoId}`, videoId: parsed.videoId, canonicalUrl: parsed.canonicalUrl }], truncated: false, failures: [] };
        const artifact: LectureAcquisitionArtifact = { schemaVersion: 1, status: "failed", request: requestShape, sourceSet, evidence: [], failures: [makeFailure("RIGHTS_REQUIRED", "Automated public video analysis approval is required")], provider, startedAt: startedAt.toISOString(), completedAt: clock().toISOString() };
        const validationIssues = validateLectureAcquisitionArtifact(artifact); if (validationIssues.length) { const issue = validationIssues[0]!; throw new LectureAcquisitionError(makeFailure("INVALID_PROVIDER_RESPONSE", `Acquisition artifact failed validation: ${issue.field}: ${issue.message}`, { provider: this.options.providerId ?? this.options.evidenceProvider.id })); } return artifact;
      }
      let sourceSet: { requested: typeof parsed; items: ResolvedVideoSource[]; truncated: boolean; failures: Failure[] };
      try {
        sourceSet = parsed.kind === "playlist" ? await this.options.playlistExpander.expand(parsed, request.limits, controller.signal) : { requested: parsed, items: [{ sourceId: `yt-video-${parsed.videoId}`, videoId: parsed.videoId, canonicalUrl: parsed.canonicalUrl }], truncated: false, failures: [] };
      } catch (e) {
        sourceSet = { requested: parsed, items: [], truncated: false, failures: [safeFailure(e, this.options.providerId ?? this.options.evidenceProvider.id)] };
      }
      const failures: Failure[] = [...sourceSet.failures]; if (sourceSet.truncated) failures.push(makeFailure("PARTIAL_SOURCE_SET", "Playlist source set was truncated", { severity: "warning" })); const evidence: EvidenceSegment[] = [];
      for (const source of sourceSet.items) { try { evidence.push(...await this.acquireSource(source, request, controller.signal)); } catch (e) { const failure = isLectureAcquisitionError(e) ? e.failure : safeFailure(e, this.options.providerId ?? this.options.evidenceProvider.id); failures.push({ ...failure, sourceId: source.sourceId }); } }
      if (!evidence.length && !failures.some(f => f.code === "ANALYSIS_FAILED")) failures.push(makeFailure("ANALYSIS_FAILED", "No evidence was acquired"));
      const status = evidence.length && !failures.length ? "succeeded" : evidence.length ? "partial" : "failed"; const artifact: LectureAcquisitionArtifact = { schemaVersion: 1, status, request: requestShape, sourceSet, evidence, failures, provider, startedAt: startedAt.toISOString(), completedAt: clock().toISOString() };
      const validationIssues = validateLectureAcquisitionArtifact(artifact); if (validationIssues.length) { const issue = validationIssues[0]!; throw new LectureAcquisitionError(makeFailure("INVALID_PROVIDER_RESPONSE", `Acquisition artifact failed validation: ${issue.field}: ${issue.message}`, { provider: this.options.providerId ?? this.options.evidenceProvider.id })); } return artifact;
    } finally { clearTimeout(timer); effectiveSignal.removeEventListener("abort", abort); }
  }
  private async acquireSource(source: ResolvedVideoSource, request: LectureAcquisitionRequest, signal: AbortSignal): Promise<EvidenceSegment[]> { let attempts = 0; const providerId = this.options.providerId ?? this.options.evidenceProvider.id; while (true) { try { if (!this.options.evidenceProvider.supports(source)) throw new AcquisitionProviderError("UNSUPPORTED_URL", "Evidence provider does not support source", { provider: "gemini-youtube", retryable: false }); const result = await this.options.evidenceProvider.acquire(source, request, signal); return this.normalize(result.raw, source, result.provider, request.limits.maxEvidenceSegmentsPerSource); } catch (e) { attempts++; if (signal.aborted) throw new LectureAcquisitionError(makeFailure("PROVIDER_TIMEOUT", "Lecture acquisition deadline exceeded or was cancelled", { provider: providerId, attempts })); if (!(isAcquisitionProviderError(e) && e.retryable) || attempts >= request.limits.maxAttempts) throw new LectureAcquisitionError({ ...safeFailure(e, providerId), attempts }); } } }
  private normalize(raw: unknown, source: ResolvedVideoSource, provider: string, cap: number): EvidenceSegment[] { let value = raw; if (typeof value === "string") { try { value = JSON.parse(value); } catch { throw new AcquisitionProviderError("INVALID_PROVIDER_RESPONSE", "provider returned malformed analysis", { provider: "gemini-youtube", retryable: false }); } } const entries = value && typeof value === "object" && Array.isArray((value as { segments?: unknown }).segments) ? (value as { segments: unknown[] }).segments : []; const out: EvidenceSegment[] = []; for (const item of entries) { if (!item || typeof item !== "object") continue; const x = item as Record<string, unknown>; const { quote, start_seconds: start, end_seconds: end, kind } = x; if (typeof quote !== "string" || !quote.length || quote.length > 4096 || typeof start !== "number" || !Number.isFinite(start) || start < 0 || typeof end !== "number" || !Number.isFinite(end) || end <= start || !(EVIDENCE_KINDS as readonly unknown[]).includes(kind) || (x.confidence !== undefined && !(EVIDENCE_CONFIDENCES as readonly unknown[]).includes(x.confidence)) || (x.language !== undefined && (typeof x.language !== "string" || x.language.length > 64))) continue; const evidenceId = createHash("sha256").update(`${source.sourceId}\0${start}\0${end}\0${String(kind)}\0${quote}`).digest("hex"); out.push({ evidenceId, sourceId: source.sourceId, location: source.canonicalUrl, provider, kind: kind as EvidenceSegment["kind"], quote, startSeconds: start, endSeconds: end, ...(x.language === undefined ? {} : { language: x.language as string }), ...(x.confidence === undefined ? {} : { confidence: x.confidence as EvidenceSegment["confidence"] }) }); if (out.length >= cap) break; } if (!entries.length || (!out.length && entries.length)) throw new AcquisitionProviderError("INVALID_PROVIDER_RESPONSE", "provider returned no valid evidence", { provider: "gemini-youtube", retryable: false }); return out; }
}
export async function createDefaultLectureAcquisitionService(cwd: string, env: Record<string, string | undefined> = process.env, overrides: { fetch?: typeof globalThis.fetch } = {}): Promise<YouTubeLectureAcquisitionService> { const config: LectureResearchConfig = await loadLectureResearchConfig(cwd, env); const fetchImpl = overrides.fetch ?? globalThis.fetch; const youtubeKey = env[config.youtube.apiKeyEnv]; const geminiKey = env[config.gemini.apiKeyEnv]; const playlistExpander: PlaylistExpander = youtubeKey ? new YouTubePlaylistExpander({ fetch: fetchImpl, apiKey: youtubeKey, endpoint: config.youtube.endpoint, maxResponseBytes: config.limits.maxResponseBytes }) : { async expand(parsed) { return { requested: parsed, items: [], truncated: false, failures: [makeFailure("PROVIDER_AUTH_MISSING", "YouTube API credentials are missing")] }; } }; const evidenceProvider: LectureEvidenceProvider = geminiKey ? new GeminiYouTubeProvider({ fetch: fetchImpl, apiKey: geminiKey, model: config.gemini.model ?? "gemini-2.5-flash", endpoint: config.gemini.endpoint, maxResponseBytes: config.limits.maxResponseBytes }) : { id: "gemini-youtube", supports: () => true, async acquire() { throw new AcquisitionProviderError("PROVIDER_AUTH_MISSING", "Gemini API credentials are missing", { provider: "gemini-youtube", retryable: false }); } }; return new YouTubeLectureAcquisitionService({ parser: { parse: parseYouTubeUrl }, playlistExpander, evidenceProvider, providerId: "gemini-youtube", model: config.gemini.model ?? "gemini-2.5-flash" }); }
