/* <!-- omp-cto-slice run=01a03ee4-7dd6-7580-8ad7-16d26dc886ba slice=workflow-v2-core --> */

export type {
  CheckpointAnswerProof,
  CheckpointRuleKind,
  ModelClassification,
  Profile,
  WorkflowName,
  WorkflowV2Digest,
  ProviderId,
  CanonicalRoot,
  ProjectRuntimeKey,
  ProviderCapability,
  HostCapability,
  AgentRef,
  AgentInventoryReservation,
  ActualAgentInventory,
  AgentInventoryAuthorityContext,
  AgentInventoryAuthority,
  ExecutableProvenance,
  ProfileIdentity,
  SessionIdentity,
  ProjectIdentity,
  WorkflowRunIdentity,
  ProviderActivationAdmission,
  ProviderActivationAdmissionExpectation,
  ProviderDescriptor,
  ProviderCatalog,
  CatalogProfile,
  ProviderRegistration,
  HostActivationContext,
  ProviderRuntimeContext,
  ProviderRuntimeFactory,
  ProviderRuntime,
  WorkflowPolicy,
  PolicyDocument,
  PolicyProviderRef,
  ScopeRule,
  ScopePatch,
  RosterOverride,
  RosterPatch,
  CommandPolicy,
  FragmentCommand,
  PolicyFragment,
  PromptContextEntry,
  MatrixWorkflowSelection,
  FixedWorkflowSelection,
  WorkflowSelection,
  PolicySnapshot,
  EffectivePolicy,
  WorkflowStateContext,
  WorkflowPrepareInput,
  WorkflowPrepareResult,
  DiagnosticSeverity,
  DiagnosticCode,
  DiagnosticOperation,
  DiagnosticEvidencePrimitive,
  DiagnosticEvidenceValue,
  WorkflowV2Diagnostic,
  DiagnosticResult,
  BindingValidatedIdentity,
  BindingDocument,
  RootEvidence,
  BindingSnapshot,
  ProjectIdentityInput,
  WorkflowRunIdentityInput,
  PathIdentity,
  AbsentPolicyPrecondition,
  PresentPolicyPrecondition,
  PolicyPrecondition,
  HostDescriptor,
  WorkflowHostOptions,
  WorkflowHost,
  AdmissionBridge,
  CanonicalCommandId,
  WorkflowToolName,
  InvocationRequest,
  ProjectValidatedDispatch,
  RunValidatedDispatch,
  ValidatedDispatch,
  ProjectDispatchResult,
  RunDispatchResult,
  ProviderDispatchResult,
  ProviderRecord,
  ProviderQuarantine,
  ProviderRegistry,
  ProviderLookupResult,
  PolicyReadResult,
  BindingReadResult,
  BindingWriteResult,
  RootBoundBindingWrite,
  PolicyFieldValue,
  FieldOperation,
  ManagementOperation,
  ManagementContext,
  ProviderListRequest,
  ProviderStatusRequest,
  ProviderSelectRequest,
  ProviderCreateRequest,
  ProviderRefreshRequest,
  ProviderMigrateRequest,
  ProviderApplyRequest,
  ProviderManagementRequest,
  ManagementProposal,
  ManagementResult,
  ProviderManagementResult,
  WorkflowOwnerKind,
  WorkflowOwnerProvenance,
  WorkflowOwnerIdentity,
  WorkflowOwnerClaim,
  WorkflowOwnerClaimResult,
} from "./types.js";

export type {
  FsAuthorityFailureReason,
  FsAuthorityFailure,
  FsAuthorityResult,
  FsDirectoryHandle,
  FsEntryIdentity,
  FsTargetFingerprint,
  FsReadSnapshot,
  FsTemporaryFile,
  PinnedFsRoot,
  FsRootDirectory,
  DescriptorRelativeNativeBackend,
  DescriptorRelativeFsAuthorityOptions,
  TrustedFsAuthority,
} from "./fs-authority.js";

export {
  createDescriptorRelativeFsAuthority,
  isTrustedFsAuthority,
} from "./fs-authority.js";

export {
  WORKFLOW_V2_DIAGNOSTIC_CODES,
  WORKFLOW_V2_DIAGNOSTIC_OPERATIONS,
  isDiagnosticEvidenceRecord,
  redactDiagnosticEvidence,
  createDiagnostic,
  successResult,
  failureResult,
  aggregateDiagnostics,
  hasDiagnosticErrors,
  isDiagnosticCode,
  isDiagnosticOperation,
  isDiagnosticSeverity,
  isWorkflowV2Diagnostic,
} from "./diagnostics.js";

export {
  isWorkflowV2Digest,
  createWorkflowV2Digest,
  isProviderId,
  createProviderId,
  isCanonicalRoot,
  createCanonicalRoot,
  validateRootEvidence,
  buildProjectIdentity,
  buildProjectWorktreeInstanceId,
  validateProjectIdentity,
  buildWorkflowRunIdentity,
  validateWorkflowRunIdentity,
  projectRuntimeKeyFor,
} from "./identity.js";

export {
  WORKFLOW_V2_CANONICAL_COMMANDS,
  WORKFLOW_V2_WORKFLOW_TOOLS,
  WORKFLOW_V2_HOST_CAPABILITIES,
  createAdmissionBridge,
} from "./admission.js";

export {
  validateProviderDescriptor,
  computeDescriptorFingerprint,
  computeCatalogContentDigest,
  validateProviderCatalog,
  buildProviderAgentInventory,
  validateProviderAgentInventory,
  preflightAgentInventory,
} from "./descriptor.js";
export { createProviderCatalog } from "../engine/profile.js";

export {
  createProviderRegistry,
  getProviderRegistry,
  publishProvider,
  lookupProvider,
  listProviders,
  listProviderQuarantine,
  validateProviderCapabilities,
} from "./registry.js";

export {
  WORKFLOW_V2_HOST_DESCRIPTOR,
  WorkflowV2HostAdmissionError,
  registerWorkflowV2Host,
  validateInvocation,
  validateProviderActivationAdmission,
  buildWorkflowPrompt,
  dispatchInvocation,
} from "./host.js";

export {
  parsePolicyDocument,
  parsePolicyBytes,
  readPolicySnapshot,
  writePolicyDocument,
  mergePolicy,
  effectivePolicyFromSnapshot,
  canonicalPolicyJson,
  computePolicySemanticHash,
  computePolicyByteHash,
  policyPath,
} from "./policy.js";

export {
  bindingFilePath,
  readRootEvidence,
  buildBindingDocument,
  readBindingSnapshot,
  writeBindingAfterConfirmation,
} from "./binding.js";

export {
  manageProvider,
  parseProviderManagementArgs,
} from "./management.js";
